# OpenSearch索引映射定义
# 根据 docs/06B-存储与图谱设计.md 中的规范

# ECS Events索引映射
ecs_events_mapping = {
    "properties": {
        "@timestamp": {"type": "date"},
        "ecs.version": {"type": "keyword"},
        "event.id": {"type": "keyword"},
        "event.kind": {"type": "keyword"},
        "event.category": {"type": "keyword"},
        "event.type": {"type": "keyword"},
        "event.action": {"type": "keyword"},
        "event.module": {"type": "keyword"},
        "event.dataset": {"type": "keyword"},
        "event.created": {"type": "date"},
        "event.ingested": {"type": "date"},
        "event.original": {"type": "text", "index": False},
        "host.id": {"type": "keyword"},
        "host.name": {"type": "keyword"},
        "user.id": {"type": "keyword"},
        "user.name": {"type": "keyword"},
        "process.entity_id": {"type": "keyword"},
        "process.pid": {"type": "long"},
        "process.parent.pid": {"type": "long"},
        "process.name": {"type": "keyword"},
        "process.command_line": {"type": "wildcard"},
        "source.ip": {"type": "ip"},
        "source.port": {"type": "long"},
        "destination.ip": {"type": "ip"},
        "destination.port": {"type": "long"},
        "network.transport": {"type": "keyword"},
        "network.direction": {"type": "keyword"},
        "dns.question.name": {"type": "wildcard"},
        "file.path": {"type": "keyword"},
        "file.hash.sha256": {"type": "keyword"},
        "session.id": {"type": "keyword"},
        "message": {"type": "text"},
    },
}

# Raw Findings索引映射
raw_findings_mapping = {
    "properties": {
        "@timestamp": {"type": "date"},
        "ecs.version": {"type": "keyword"},
        "event.id": {"type": "keyword"},
        "event.kind": {"type": "keyword"},
        "event.category": {"type": "keyword"},
        "event.type": {"type": "keyword"},
        "event.action": {"type": "keyword"},
        "event.dataset": {"type": "keyword"},
        "event.severity": {"type": "integer"},
        "event.created": {"type": "date"},
        "event.ingested": {"type": "date"},
        "rule.id": {"type": "keyword"},
        "rule.name": {"type": "keyword"},
        "rule.version": {"type": "keyword"},
        "rule.ruleset": {"type": "keyword"},
        "threat.tactic.id": {"type": "keyword"},
        "threat.tactic.name": {"type": "keyword"},
        "threat.technique.id": {"type": "keyword"},
        "threat.technique.name": {"type": "keyword"},
        "custom.finding.stage": {"type": "keyword"},
        "custom.finding.providers": {"type": "keyword"},
        "custom.confidence": {"type": "float"},
        "custom.evidence.event_ids": {"type": "keyword"},
        "host.id": {"type": "keyword"},
        "host.name": {"type": "keyword"},
        "user.id": {"type": "keyword"},
        "user.name": {"type": "keyword"},
        "process.entity_id": {"type": "keyword"},
        "source.ip": {"type": "ip"},
        "destination.ip": {"type": "ip"},
        "destination.port": {"type": "long"},
        "dns.question.name": {"type": "wildcard"},
        "file.path": {"type": "keyword"},
        "file.hash.sha256": {"type": "keyword"},
        "message": {"type": "text"},
    },
}

# Canonical Findings索引映射
canonical_findings_mapping = {
    "properties": {
        "@timestamp": {"type": "date"},
        "ecs.version": {"type": "keyword"},
        "event.id": {"type": "keyword"},
        "event.kind": {"type": "keyword"},
        "event.category": {"type": "keyword"},
        "event.type": {"type": "keyword"},
        "event.action": {"type": "keyword"},
        "event.dataset": {"type": "keyword"},
        "event.severity": {"type": "integer"},
        "event.created": {"type": "date"},
        "event.ingested": {"type": "date"},
        "rule.id": {"type": "keyword"},
        "rule.name": {"type": "keyword"},
        "rule.version": {"type": "keyword"},
        "threat.tactic.id": {"type": "keyword"},
        "threat.tactic.name": {"type": "keyword"},
        "threat.technique.id": {"type": "keyword"},
        "threat.technique.name": {"type": "keyword"},
        "custom.finding.stage": {"type": "keyword"},
        "custom.finding.providers": {"type": "keyword"},
        "custom.finding.fingerprint": {"type": "keyword"},
        "custom.confidence": {"type": "float"},
        "custom.evidence.event_ids": {"type": "keyword"},
        "host.id": {"type": "keyword"},
        "host.name": {"type": "keyword"},
        "user.id": {"type": "keyword"},
        "user.name": {"type": "keyword"},
        "process.entity_id": {"type": "keyword"},
        "source.ip": {"type": "ip"},
        "destination.ip": {"type": "ip"},
        "destination.port": {"type": "long"},
        "dns.question.name": {"type": "wildcard"},
        "file.path": {"type": "keyword"},
        "file.hash.sha256": {"type": "keyword"},
        "message": {"type": "text"},
    },
}

# Attack Chains索引映射
attack_chains_mapping = {
    "properties": {
        "@timestamp": {"type": "date"},
        "chain.id": {"type": "keyword"},
        "chain.start_ts": {"type": "date"},
        "chain.end_ts": {"type": "date"},
        "chain.stages": {
            "type": "nested",
            "properties": {
                "tactic.id": {"type": "keyword"},
                "tactic.name": {"type": "keyword"},
                "technique.id": {"type": "keyword"},
                "technique.name": {"type": "keyword"},
                "timestamp": {"type": "date"},
                "key_entities": {"type": "keyword"},
                "evidence_event_ids": {"type": "keyword"},
            },
        },
        "chain.key_path": {
            "type": "nested",
            "properties": {
                "node_type": {"type": "keyword"},
                "node_id": {"type": "keyword"},
                "edge_type": {"type": "keyword"},
                "timestamp": {"type": "date"},
            },
        },
        "chain.similar_apts": {
            "type": "nested",
            "properties": {
                "intrusion_set.id": {"type": "keyword"},
                "intrusion_set.name": {"type": "keyword"},
                "similarity_score": {"type": "float"},
                "top_techniques": {"type": "keyword"},
            },
        },
    },
}

# Client Registry索引映射
client_registry_mapping = {
    "properties": {
        "@timestamp": {"type": "date"},
        "client.id": {"type": "keyword"},
        "client.listen_url": {"type": "keyword"},
        "client.version": {"type": "keyword"},
        "client.host.id": {"type": "keyword"},
        "client.host.name": {"type": "keyword"},
        "client.capabilities.wazuh": {"type": "boolean"},
        "client.capabilities.falco": {"type": "boolean"},
        "client.capabilities.suricata": {"type": "boolean"},
        "client.token_hash": {"type": "keyword"},
        "poll.cursor": {"type": "keyword"},
        "poll.last_seen": {"type": "date"},
        "poll.last_error": {"type": "text", "index": False},
        "poll.status": {"type": "keyword"},
    },
}
